CREATE TABLE ERS_REIMBURSEMENT_STATUS
(
    REIMB_STATUS_ID NUMBER,
    REIMB_STATUS VARCHAR2(10) NOT NULL,
    
    CONSTRAINT REIMB_STATUS_PK PRIMARY KEY (REIMB_STATUS_ID)
);

CREATE TABLE ERS_REIMBURSEMENT_TYPE
(
    REIMB_TYPE_ID NUMBER,
    REIMB_TYPE VARCHAR2(10) NOT NULL,
    
    CONSTRAINT REIMB_TYPE_PK PRIMARY KEY (REIMB_TYPE_ID)
);


CREATE TABLE ERS_USER_ROLES
(
    ERS_USER_ROLE_ID NUMBER,
    USER_ROLE VARCHAR(10) NOT NULL,
    
    CONSTRAINT USER_ROLE_PK PRIMARY KEY (ERS_USER_ROLE_ID)
);

CREATE TABLE ERS_USERS
(
    ERS_USERS_ID NUMBER,
    ERS_USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    ERS_PASSWORD VARCHAR2(50) NOT NULL,
    USER_FIRST_NAME VARCHAR2(100) NOT NULL,
    USER_LAST_NAME VARCHAR2(100) NOT NULL,
    USER_EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    USER_ROLE_ID NUMBER NOT NULL,
    
    CONSTRAINT ERS_USERS_PK PRIMARY KEY (ERS_USERS_ID),
    
    CONSTRAINT USER_ROLES_FK FOREIGN KEY (USER_ROLE_ID)
    REFERENCES ERS_USER_ROLES(ERS_USER_ROLE_ID)--,
    
    --INDEX ERS_USERNAME,
    --INDEX USER_EMAIL
);

CREATE TABLE ERS_REIMBURSEMENT
(
    REIMB_ID NUMBER,
    REIMB_AMMOUNT NUMBER NOT NULL,
    REIMB_SUBMITTED TIMESTAMP NOT NULL,
    REIMB_RESOLVED TIMESTAMP,
    REIMB_DESCRIPTION VARCHAR(250),
    REIMB_RECEIPT BLOB,
    REIMB_AUTHOR NOT NULL,
    REIMB_RESOLVER NUMBER,
    REIMB_STATUS_ID NUMBER NOT NULL,
    REIMB_TYPE_ID NUMBER NOT NULL,
    
    CONSTRAINT pk_for_table_checking_account PRIMARY KEY (REIMB_ID),
    
    CONSTRAINT fk_for_rbAuthor FOREIGN KEY (REIMB_AUTHOR)
    REFERENCES ERS_USERS(ERS_USERS_ID),
    
    CONSTRAINT fk_for_rbResolver FOREIGN KEY (REIMB_RESOLVER)
    REFERENCES ERS_USERS(ERS_USERS_ID),
    
    CONSTRAINT fk_for_rbStatusId FOREIGN KEY (REIMB_STATUS_ID)
    REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID),
    
    CONSTRAINT ERS_REIMBURSEMENT_TYPE_FK FOREIGN KEY (REIMB_TYPE_ID)
    REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID)
);

CREATE SEQUENCE ERS_REIMB_ID_SEQ
MINVALUE 0 START WITH 0 INCREMENT BY 1 ORDER NOMAXVALUE;

CREATE SEQUENCE ERS_USERS_ID_SEQ
MINVALUE 0 START WITH 0 INCREMENT BY 1 ORDER NOMAXVALUE;

CREATE SEQUENCE ERS_USER_ROLE_ID_SEQ
MINVALUE 0 START WITH 0 INCREMENT BY 1 ORDER NOMAXVALUE;

CREATE SEQUENCE ERS_REIMB_TYPE_ID_SEQ
MINVALUE 0 START WITH 0 INCREMENT BY 1 ORDER NOMAXVALUE;

CREATE SEQUENCE ERS_REIMB_STATUS_ID_SEQ
MINVALUE 0 START WITH 0 INCREMENT BY 1 ORDER NOMAXVALUE;

CREATE TRIGGER UNIQUE_ERS_REIMB_ID
BEFORE INSERT ON ERS_REIMBURSEMENT
FOR EACH ROW
BEGIN
    :new.REIMB_ID := ERS_REIMB_ID_SEQ.NEXTVAL;
END;
/

CREATE TRIGGER UNIQUE_ERS_USERS_ID
BEFORE INSERT ON ERS_USERS
FOR EACH ROW
BEGIN
    :new.ERS_USERS_ID := ERS_USERS_ID_SEQ.NEXTVAL;
END;
/

CREATE TRIGGER UNIQUE_ERS_REIMB_STATUS_ID
BEFORE INSERT ON ERS_REIMBURSEMENT_STATUS
FOR EACH ROW
BEGIN
    :new.REIMB_STATUS_ID := ERS_REIMB_STATUS_ID_SEQ.NEXTVAL;
END;
/

CREATE TRIGGER UNIQUE_ERS_REIMB_TYPE_ID
BEFORE INSERT ON ERS_REIMBURSEMENT_TYPE
FOR EACH ROW
BEGIN
    :new.REIMB_TYPE_ID := ERS_REIMB_TYPE_ID_SEQ.NEXTVAL;
END;
/

CREATE TRIGGER UNIQUE_ERS_USER_ROLE_ID
BEFORE INSERT ON ERS_USER_ROLES
FOR EACH ROW
BEGIN
    :new.ERS_USER_ROLE_ID := ERS_USER_ROLE_ID_SEQ.NEXTVAL;
END;
/

